// Code generated by protoc-gen-go. DO NOT EDIT.
// source: commerce_listings.proto

package gw2api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// ArticleListing includes the id of the listing and a list of buys and sells
type Listings struct {
	Id                   uint32            `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Buys                 []*Listings_BUYS  `protobuf:"bytes,2,rep,name=buys,proto3" json:"buys,omitempty"`
	Sells                []*Listings_SELLS `protobuf:"bytes,3,rep,name=sells,proto3" json:"sells,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Listings) Reset()         { *m = Listings{} }
func (m *Listings) String() string { return proto.CompactTextString(m) }
func (*Listings) ProtoMessage()    {}
func (*Listings) Descriptor() ([]byte, []int) {
	return fileDescriptor_472404e8ab389c17, []int{0}
}

func (m *Listings) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Listings.Unmarshal(m, b)
}
func (m *Listings) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Listings.Marshal(b, m, deterministic)
}
func (m *Listings) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Listings.Merge(m, src)
}
func (m *Listings) XXX_Size() int {
	return xxx_messageInfo_Listings.Size(m)
}
func (m *Listings) XXX_DiscardUnknown() {
	xxx_messageInfo_Listings.DiscardUnknown(m)
}

var xxx_messageInfo_Listings proto.InternalMessageInfo

func (m *Listings) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Listings) GetBuys() []*Listings_BUYS {
	if m != nil {
		return m.Buys
	}
	return nil
}

func (m *Listings) GetSells() []*Listings_SELLS {
	if m != nil {
		return m.Sells
	}
	return nil
}

// Listing includes number of listings at the unit price with respective quantity
type Listings_BUYS struct {
	Listings             uint32   `protobuf:"varint,1,opt,name=listings,proto3" json:"listings,omitempty"`
	UnitPrice            uint32   `protobuf:"varint,2,opt,name=unit_price,json=unitPrice,proto3" json:"unit_price,omitempty"`
	Quantity             uint32   `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Listings_BUYS) Reset()         { *m = Listings_BUYS{} }
func (m *Listings_BUYS) String() string { return proto.CompactTextString(m) }
func (*Listings_BUYS) ProtoMessage()    {}
func (*Listings_BUYS) Descriptor() ([]byte, []int) {
	return fileDescriptor_472404e8ab389c17, []int{0, 0}
}

func (m *Listings_BUYS) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Listings_BUYS.Unmarshal(m, b)
}
func (m *Listings_BUYS) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Listings_BUYS.Marshal(b, m, deterministic)
}
func (m *Listings_BUYS) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Listings_BUYS.Merge(m, src)
}
func (m *Listings_BUYS) XXX_Size() int {
	return xxx_messageInfo_Listings_BUYS.Size(m)
}
func (m *Listings_BUYS) XXX_DiscardUnknown() {
	xxx_messageInfo_Listings_BUYS.DiscardUnknown(m)
}

var xxx_messageInfo_Listings_BUYS proto.InternalMessageInfo

func (m *Listings_BUYS) GetListings() uint32 {
	if m != nil {
		return m.Listings
	}
	return 0
}

func (m *Listings_BUYS) GetUnitPrice() uint32 {
	if m != nil {
		return m.UnitPrice
	}
	return 0
}

func (m *Listings_BUYS) GetQuantity() uint32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

// Listing includes number of listings at the unit price with respective quantity
type Listings_SELLS struct {
	Listings             uint32   `protobuf:"varint,1,opt,name=listings,proto3" json:"listings,omitempty"`
	UnitPrice            uint32   `protobuf:"varint,2,opt,name=unit_price,json=unitPrice,proto3" json:"unit_price,omitempty"`
	Quantity             uint32   `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Listings_SELLS) Reset()         { *m = Listings_SELLS{} }
func (m *Listings_SELLS) String() string { return proto.CompactTextString(m) }
func (*Listings_SELLS) ProtoMessage()    {}
func (*Listings_SELLS) Descriptor() ([]byte, []int) {
	return fileDescriptor_472404e8ab389c17, []int{0, 1}
}

func (m *Listings_SELLS) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Listings_SELLS.Unmarshal(m, b)
}
func (m *Listings_SELLS) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Listings_SELLS.Marshal(b, m, deterministic)
}
func (m *Listings_SELLS) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Listings_SELLS.Merge(m, src)
}
func (m *Listings_SELLS) XXX_Size() int {
	return xxx_messageInfo_Listings_SELLS.Size(m)
}
func (m *Listings_SELLS) XXX_DiscardUnknown() {
	xxx_messageInfo_Listings_SELLS.DiscardUnknown(m)
}

var xxx_messageInfo_Listings_SELLS proto.InternalMessageInfo

func (m *Listings_SELLS) GetListings() uint32 {
	if m != nil {
		return m.Listings
	}
	return 0
}

func (m *Listings_SELLS) GetUnitPrice() uint32 {
	if m != nil {
		return m.UnitPrice
	}
	return 0
}

func (m *Listings_SELLS) GetQuantity() uint32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func init() {
	proto.RegisterType((*Listings)(nil), "gw2api.Listings")
	proto.RegisterType((*Listings_BUYS)(nil), "gw2api.Listings.BUYS")
	proto.RegisterType((*Listings_SELLS)(nil), "gw2api.Listings.SELLS")
}

func init() { proto.RegisterFile("commerce_listings.proto", fileDescriptor_472404e8ab389c17) }

var fileDescriptor_472404e8ab389c17 = []byte{
	// 205 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4f, 0xce, 0xcf, 0xcd,
	0x4d, 0x2d, 0x4a, 0x4e, 0x8d, 0xcf, 0xc9, 0x2c, 0x2e, 0xc9, 0xcc, 0x4b, 0x2f, 0xd6, 0x2b, 0x28,
	0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4b, 0x2f, 0x37, 0x4a, 0x2c, 0xc8, 0x54, 0xda, 0xc4, 0xc4, 0xc5,
	0xe1, 0x03, 0x95, 0x12, 0xe2, 0xe3, 0x62, 0xca, 0x4c, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0d,
	0x62, 0xca, 0x4c, 0x11, 0xd2, 0xe4, 0x62, 0x49, 0x2a, 0xad, 0x2c, 0x96, 0x60, 0x52, 0x60, 0xd6,
	0xe0, 0x36, 0x12, 0xd5, 0x83, 0xe8, 0xd1, 0x83, 0xa9, 0xd7, 0x73, 0x0a, 0x8d, 0x0c, 0x0e, 0x02,
	0x2b, 0x11, 0xd2, 0xe1, 0x62, 0x2d, 0x4e, 0xcd, 0xc9, 0x29, 0x96, 0x60, 0x06, 0xab, 0x15, 0xc3,
	0x50, 0x1b, 0xec, 0xea, 0xe3, 0x13, 0x1c, 0x04, 0x51, 0x24, 0x15, 0xcb, 0xc5, 0x02, 0xd2, 0x2b,
	0x24, 0xc5, 0xc5, 0x01, 0x73, 0x17, 0xd4, 0x5a, 0x38, 0x5f, 0x48, 0x96, 0x8b, 0xab, 0x34, 0x2f,
	0xb3, 0x24, 0xbe, 0xa0, 0x28, 0x33, 0x39, 0x55, 0x82, 0x09, 0x2c, 0xcb, 0x09, 0x12, 0x09, 0x00,
	0x09, 0x80, 0xb4, 0x16, 0x96, 0x26, 0xe6, 0x95, 0x64, 0x96, 0x54, 0x4a, 0x30, 0x43, 0xb4, 0xc2,
	0xf8, 0x52, 0x71, 0x5c, 0xac, 0x60, 0xeb, 0x68, 0x64, 0x7e, 0x12, 0x1b, 0x38, 0x0c, 0x8d, 0x01,
	0x01, 0x00, 0x00, 0xff, 0xff, 0xe2, 0xba, 0xd3, 0x54, 0x5e, 0x01, 0x00, 0x00,
}
