// Code generated by protoc-gen-go. DO NOT EDIT.
// source: item.proto

package gw2api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Item struct {
	ID                   uint32   `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Icon                 string   `protobuf:"bytes,3,opt,name=Icon,proto3" json:"Icon,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=Description,proto3" json:"Description,omitempty"`
	Type                 string   `protobuf:"bytes,5,opt,name=Type,proto3" json:"Type,omitempty"`
	Rarity               string   `protobuf:"bytes,6,opt,name=Rarity,proto3" json:"Rarity,omitempty"`
	Level                uint32   `protobuf:"varint,7,opt,name=Level,proto3" json:"Level,omitempty"`
	VendorValue          uint32   `protobuf:"varint,8,opt,name=VendorValue,proto3" json:"VendorValue,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Item) Reset()         { *m = Item{} }
func (m *Item) String() string { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()    {}
func (*Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_6007f868cf6553df, []int{0}
}

func (m *Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Item.Unmarshal(m, b)
}
func (m *Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Item.Marshal(b, m, deterministic)
}
func (m *Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Item.Merge(m, src)
}
func (m *Item) XXX_Size() int {
	return xxx_messageInfo_Item.Size(m)
}
func (m *Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Item.DiscardUnknown(m)
}

var xxx_messageInfo_Item proto.InternalMessageInfo

func (m *Item) GetID() uint32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Item) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Item) GetIcon() string {
	if m != nil {
		return m.Icon
	}
	return ""
}

func (m *Item) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Item) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Item) GetRarity() string {
	if m != nil {
		return m.Rarity
	}
	return ""
}

func (m *Item) GetLevel() uint32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *Item) GetVendorValue() uint32 {
	if m != nil {
		return m.VendorValue
	}
	return 0
}

func init() {
	proto.RegisterType((*Item)(nil), "gw2api.Item")
}

func init() { proto.RegisterFile("item.proto", fileDescriptor_6007f868cf6553df) }

var fileDescriptor_6007f868cf6553df = []byte{
	// 184 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8f, 0xb1, 0x0a, 0xc2, 0x30,
	0x14, 0x45, 0x49, 0x6d, 0xa3, 0x3e, 0xd1, 0x21, 0x88, 0xbc, 0xb1, 0x38, 0x75, 0x72, 0xd0, 0x5f,
	0xe8, 0x12, 0x10, 0x87, 0x22, 0xdd, 0x63, 0x7d, 0x48, 0xa0, 0x6d, 0x42, 0x8c, 0x4a, 0xff, 0xcf,
	0x0f, 0x93, 0xa4, 0x0e, 0xdd, 0xce, 0x3d, 0x97, 0x4b, 0xf2, 0x00, 0xb4, 0xa7, 0xee, 0x60, 0x9d,
	0xf1, 0x46, 0xf0, 0xc7, 0xe7, 0xa8, 0xac, 0xde, 0x7f, 0x19, 0xa4, 0xd2, 0x53, 0x27, 0x36, 0x90,
	0xc8, 0x12, 0x59, 0xce, 0x8a, 0x75, 0x95, 0xc8, 0x52, 0x08, 0x48, 0x2f, 0xaa, 0x23, 0x4c, 0x72,
	0x56, 0x2c, 0xab, 0xc8, 0xc1, 0xc9, 0xc6, 0xf4, 0x38, 0x1b, 0x5d, 0x60, 0x91, 0xc3, 0xaa, 0xa4,
	0x67, 0xe3, 0xb4, 0xf5, 0xda, 0xf4, 0x98, 0xc6, 0x6a, 0xaa, 0xc2, 0xea, 0x3a, 0x58, 0xc2, 0x6c,
	0x5c, 0x05, 0x16, 0x3b, 0xe0, 0x95, 0x72, 0xda, 0x0f, 0xc8, 0xa3, 0xfd, 0x27, 0xb1, 0x85, 0xec,
	0x4c, 0x6f, 0x6a, 0x71, 0x1e, 0x3f, 0x32, 0x86, 0xf0, 0x46, 0x4d, 0xfd, 0xdd, 0xb8, 0x5a, 0xb5,
	0x2f, 0xc2, 0x45, 0xec, 0xa6, 0xea, 0xc6, 0xe3, 0x55, 0xa7, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x48, 0x42, 0x2c, 0xd8, 0xe3, 0x00, 0x00, 0x00,
}
