// Code generated by protoc-gen-go. DO NOT EDIT.
// source: item_present.proto

package main

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Item struct {
	ID                   int32    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Icon                 string   `protobuf:"bytes,3,opt,name=Icon,proto3" json:"Icon,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=Description,proto3" json:"Description,omitempty"`
	Type                 string   `protobuf:"bytes,5,opt,name=Type,proto3" json:"Type,omitempty"`
	Rarity               string   `protobuf:"bytes,6,opt,name=Rarity,proto3" json:"Rarity,omitempty"`
	Level                int32    `protobuf:"varint,7,opt,name=Level,proto3" json:"Level,omitempty"`
	VendorValue          int32    `protobuf:"varint,8,opt,name=VendorValue,proto3" json:"VendorValue,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Item) Reset()         { *m = Item{} }
func (m *Item) String() string { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()    {}
func (*Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_12063e307637a3d8, []int{0}
}

func (m *Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Item.Unmarshal(m, b)
}
func (m *Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Item.Marshal(b, m, deterministic)
}
func (m *Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Item.Merge(m, src)
}
func (m *Item) XXX_Size() int {
	return xxx_messageInfo_Item.Size(m)
}
func (m *Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Item.DiscardUnknown(m)
}

var xxx_messageInfo_Item proto.InternalMessageInfo

func (m *Item) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Item) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Item) GetIcon() string {
	if m != nil {
		return m.Icon
	}
	return ""
}

func (m *Item) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Item) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Item) GetRarity() string {
	if m != nil {
		return m.Rarity
	}
	return ""
}

func (m *Item) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *Item) GetVendorValue() int32 {
	if m != nil {
		return m.VendorValue
	}
	return 0
}

type ItemIdFilter struct {
	ItemId               uint32   `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ItemIdFilter) Reset()         { *m = ItemIdFilter{} }
func (m *ItemIdFilter) String() string { return proto.CompactTextString(m) }
func (*ItemIdFilter) ProtoMessage()    {}
func (*ItemIdFilter) Descriptor() ([]byte, []int) {
	return fileDescriptor_12063e307637a3d8, []int{1}
}

func (m *ItemIdFilter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ItemIdFilter.Unmarshal(m, b)
}
func (m *ItemIdFilter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ItemIdFilter.Marshal(b, m, deterministic)
}
func (m *ItemIdFilter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ItemIdFilter.Merge(m, src)
}
func (m *ItemIdFilter) XXX_Size() int {
	return xxx_messageInfo_ItemIdFilter.Size(m)
}
func (m *ItemIdFilter) XXX_DiscardUnknown() {
	xxx_messageInfo_ItemIdFilter.DiscardUnknown(m)
}

var xxx_messageInfo_ItemIdFilter proto.InternalMessageInfo

func (m *ItemIdFilter) GetItemId() uint32 {
	if m != nil {
		return m.ItemId
	}
	return 0
}

type ItemIds struct {
	ItemId               uint32   `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ItemIds) Reset()         { *m = ItemIds{} }
func (m *ItemIds) String() string { return proto.CompactTextString(m) }
func (*ItemIds) ProtoMessage()    {}
func (*ItemIds) Descriptor() ([]byte, []int) {
	return fileDescriptor_12063e307637a3d8, []int{2}
}

func (m *ItemIds) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ItemIds.Unmarshal(m, b)
}
func (m *ItemIds) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ItemIds.Marshal(b, m, deterministic)
}
func (m *ItemIds) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ItemIds.Merge(m, src)
}
func (m *ItemIds) XXX_Size() int {
	return xxx_messageInfo_ItemIds.Size(m)
}
func (m *ItemIds) XXX_DiscardUnknown() {
	xxx_messageInfo_ItemIds.DiscardUnknown(m)
}

var xxx_messageInfo_ItemIds proto.InternalMessageInfo

func (m *ItemIds) GetItemId() uint32 {
	if m != nil {
		return m.ItemId
	}
	return 0
}

func init() {
	proto.RegisterType((*Item)(nil), "main.Item")
	proto.RegisterType((*ItemIdFilter)(nil), "main.ItemIdFilter")
	proto.RegisterType((*ItemIds)(nil), "main.ItemIds")
}

func init() { proto.RegisterFile("item_present.proto", fileDescriptor_12063e307637a3d8) }

var fileDescriptor_12063e307637a3d8 = []byte{
	// 294 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0x9b, 0x9a, 0xa6, 0x75, 0x6a, 0x3d, 0x0c, 0x52, 0x97, 0x7a, 0x29, 0xb9, 0xd8, 0xd3,
	0x56, 0x14, 0xff, 0x41, 0x55, 0x16, 0x44, 0x24, 0x48, 0xaf, 0x92, 0x36, 0x63, 0x59, 0x48, 0xb2,
	0x61, 0xb3, 0x2d, 0xe4, 0xff, 0xf9, 0xc3, 0x64, 0x76, 0x15, 0x7b, 0xe9, 0x6d, 0xf6, 0x7b, 0xef,
	0x31, 0x3b, 0x0f, 0x50, 0x3b, 0xaa, 0x3e, 0x1b, 0x4b, 0x2d, 0xd5, 0x4e, 0x36, 0xd6, 0x38, 0x83,
	0x71, 0x95, 0xeb, 0x7a, 0x76, 0xb3, 0x33, 0x66, 0x57, 0xd2, 0xd2, 0xb3, 0xcd, 0xfe, 0x6b, 0x49,
	0x55, 0xe3, 0xba, 0x60, 0x49, 0xbf, 0x23, 0x88, 0x95, 0xa3, 0x0a, 0x2f, 0xa1, 0xaf, 0x56, 0x22,
	0x9a, 0x47, 0x8b, 0x41, 0xd6, 0x57, 0x2b, 0x44, 0x88, 0xdf, 0xf2, 0x8a, 0x44, 0x7f, 0x1e, 0x2d,
	0xce, 0x33, 0x3f, 0x33, 0x53, 0x5b, 0x53, 0x8b, 0xb3, 0xc0, 0x78, 0xc6, 0x39, 0x8c, 0x57, 0xd4,
	0x6e, 0xad, 0x6e, 0x9c, 0x36, 0xb5, 0x88, 0xbd, 0x74, 0x8c, 0x38, 0xf5, 0xd1, 0x35, 0x24, 0x06,
	0x21, 0xc5, 0x33, 0x4e, 0x21, 0xc9, 0x72, 0xab, 0x5d, 0x27, 0x12, 0x4f, 0x7f, 0x5f, 0x78, 0x05,
	0x83, 0x57, 0x3a, 0x50, 0x29, 0x86, 0xfe, 0x23, 0xe1, 0xc1, 0x3b, 0xd6, 0x54, 0x17, 0xc6, 0xae,
	0xf3, 0x72, 0x4f, 0x62, 0xe4, 0xb5, 0x63, 0x94, 0xde, 0xc2, 0x05, 0x5f, 0xa1, 0x8a, 0x67, 0x5d,
	0x3a, 0xb2, 0x78, 0x0d, 0x43, 0xdf, 0x87, 0x2e, 0xfc, 0x49, 0x93, 0x2c, 0xd1, 0x5e, 0x4e, 0x53,
	0x18, 0x06, 0x63, 0x7b, 0xd2, 0x73, 0x7f, 0x80, 0x31, 0x7b, 0xde, 0x43, 0x97, 0x78, 0x07, 0xa3,
	0x1d, 0x39, 0x26, 0x2d, 0x4e, 0x65, 0x28, 0x53, 0xfe, 0x95, 0x29, 0x9f, 0xb8, 0xcc, 0x19, 0x48,
	0xae, 0x5a, 0xb2, 0x29, 0xed, 0xe1, 0x23, 0xc0, 0x4b, 0x48, 0xf0, 0x9e, 0x53, 0x99, 0xc9, 0x7f,
	0x46, 0x15, 0x6d, 0xda, 0xdb, 0x24, 0xde, 0xf0, 0xf0, 0x13, 0x00, 0x00, 0xff, 0xff, 0xb8, 0x82,
	0x58, 0xc1, 0xcb, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ItemPresentClient is the client API for ItemPresent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ItemPresentClient interface {
	// Create a new event to the event store
	GetItems(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Item, error)
	// Get all events for the given aggregate and event
	GetItemIds(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ItemIds, error)
}

type itemPresentClient struct {
	cc *grpc.ClientConn
}

func NewItemPresentClient(cc *grpc.ClientConn) ItemPresentClient {
	return &itemPresentClient{cc}
}

func (c *itemPresentClient) GetItems(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Item, error) {
	out := new(Item)
	err := c.cc.Invoke(ctx, "/main.ItemPresent/getItems", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemPresentClient) GetItemIds(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ItemIds, error) {
	out := new(ItemIds)
	err := c.cc.Invoke(ctx, "/main.ItemPresent/GetItemIds", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ItemPresentServer is the server API for ItemPresent service.
type ItemPresentServer interface {
	// Create a new event to the event store
	GetItems(context.Context, *empty.Empty) (*Item, error)
	// Get all events for the given aggregate and event
	GetItemIds(context.Context, *empty.Empty) (*ItemIds, error)
}

// UnimplementedItemPresentServer can be embedded to have forward compatible implementations.
type UnimplementedItemPresentServer struct {
}

func (*UnimplementedItemPresentServer) GetItems(ctx context.Context, req *empty.Empty) (*Item, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetItems not implemented")
}
func (*UnimplementedItemPresentServer) GetItemIds(ctx context.Context, req *empty.Empty) (*ItemIds, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetItemIds not implemented")
}

func RegisterItemPresentServer(s *grpc.Server, srv ItemPresentServer) {
	s.RegisterService(&_ItemPresent_serviceDesc, srv)
}

func _ItemPresent_GetItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemPresentServer).GetItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.ItemPresent/GetItems",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemPresentServer).GetItems(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ItemPresent_GetItemIds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemPresentServer).GetItemIds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.ItemPresent/GetItemIds",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemPresentServer).GetItemIds(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _ItemPresent_serviceDesc = grpc.ServiceDesc{
	ServiceName: "main.ItemPresent",
	HandlerType: (*ItemPresentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getItems",
			Handler:    _ItemPresent_GetItems_Handler,
		},
		{
			MethodName: "GetItemIds",
			Handler:    _ItemPresent_GetItemIds_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "item_present.proto",
}
