version: "3.6"

services:
  eventstores:
    build: "."
    command: "eventstores"
    ports:
    - "50051:50051"
    depends_on:
    - "nats"
    - "roach1"

  eventstores2:
    build: "."
    command: "eventstores2"
    ports:
    - "50052:50052"
    depends_on:
    - "nats"
    - "roach1"

  create_itemdetails_orders:
    build: "."
    command: "create_itemdetails_orders"
    depends_on:
    - "nats"
    - "roach1"
    - "eventstores"
    - "eventstores2"
    - "cuttle"

  fetcher_itemdetails_orders:
    build: "."
    command: "fetcher_itemdetails_orders"
    depends_on:
    - "nats"
    - "roach1"
    - "eventstores"
    - "eventstores2"
    - "cuttle"

  persister_itemdetails:
    build: "."
    command: "persister_itemdetails"
    depends_on:
    - "nats"
    - "roach1"
    - "eventstores"
    - "cuttle"


#  redis:
#    image: redis:4.0.5-alpine
#    command: ["redis-server", "--appendonly", "yes"]
#    hostname: redis
#    ports:
#    - "6379:6379"
#    networks:
#    - redis-net
#    volumes:
#    - redis-data:/data
#
#  statsd:
#    image: "omesser/statsd"
#    restart: "always"
#    ports:
#    - "8125:8125"

  cuttle:
    container_name: cuttle
    image: cuttle
    ports:
    - "3128:3128"

  nats:
    image: "nats-streaming:0.9.2"
    restart: "always"
    ports:
    - "4222:4222"
    - "8222:8222"

  roach1:
    container_name: roach1
    image: cockroachdb/cockroach:v1.1.3
    command: start --insecure
    ports:
    - "26257:26257"
    - "8080:8080"
    volumes:
    - ./cockroach-data/roach1:/cockroach/cockroach-data
    networks:
      roachnet:
        aliases:
        - roach1

  roach2:
    container_name: roach2
    image: cockroachdb/cockroach:v1.1.3
    command: start --insecure --join=roach1
    volumes:
    - ./cockroach-data/roach2:/cockroach/cockroach-data
    depends_on:
    - roach1
    networks:
      roachnet:
        aliases:
        - roach2

networks:
  roachnet:
    driver: bridge