// Code generated by protoc-gen-go. DO NOT EDIT.
// source: commerce_prices.proto

package persist

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// ArticlePrice Listings for a specific item (highest buy, lowest sell)
type Prices struct {
	Id                   uint32        `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Whitelisted          bool          `protobuf:"varint,2,opt,name=whitelisted,proto3" json:"whitelisted,omitempty"`
	FetchDatetime        int64         `protobuf:"varint,3,opt,name=fetch_datetime,json=fetchDatetime,proto3" json:"fetch_datetime,omitempty"`
	Buys                 *Prices_BUYS  `protobuf:"bytes,4,opt,name=buys,proto3" json:"buys,omitempty"`
	Sells                *Prices_SELLS `protobuf:"bytes,5,opt,name=sells,proto3" json:"sells,omitempty"`
	AggregateId          string        `protobuf:"bytes,6,opt,name=aggregate_id,json=aggregateId,proto3" json:"aggregate_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Prices) Reset()         { *m = Prices{} }
func (m *Prices) String() string { return proto.CompactTextString(m) }
func (*Prices) ProtoMessage()    {}
func (*Prices) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff8ce280720193cf, []int{0}
}

func (m *Prices) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Prices.Unmarshal(m, b)
}
func (m *Prices) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Prices.Marshal(b, m, deterministic)
}
func (m *Prices) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Prices.Merge(m, src)
}
func (m *Prices) XXX_Size() int {
	return xxx_messageInfo_Prices.Size(m)
}
func (m *Prices) XXX_DiscardUnknown() {
	xxx_messageInfo_Prices.DiscardUnknown(m)
}

var xxx_messageInfo_Prices proto.InternalMessageInfo

func (m *Prices) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Prices) GetWhitelisted() bool {
	if m != nil {
		return m.Whitelisted
	}
	return false
}

func (m *Prices) GetFetchDatetime() int64 {
	if m != nil {
		return m.FetchDatetime
	}
	return 0
}

func (m *Prices) GetBuys() *Prices_BUYS {
	if m != nil {
		return m.Buys
	}
	return nil
}

func (m *Prices) GetSells() *Prices_SELLS {
	if m != nil {
		return m.Sells
	}
	return nil
}

func (m *Prices) GetAggregateId() string {
	if m != nil {
		return m.AggregateId
	}
	return ""
}

// Price includes quantity and the high/low price
type Prices_BUYS struct {
	Quantity             uint32   `protobuf:"varint,1,opt,name=quantity,proto3" json:"quantity,omitempty"`
	UnitPrice            uint32   `protobuf:"varint,2,opt,name=unit_price,json=unitPrice,proto3" json:"unit_price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Prices_BUYS) Reset()         { *m = Prices_BUYS{} }
func (m *Prices_BUYS) String() string { return proto.CompactTextString(m) }
func (*Prices_BUYS) ProtoMessage()    {}
func (*Prices_BUYS) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff8ce280720193cf, []int{0, 0}
}

func (m *Prices_BUYS) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Prices_BUYS.Unmarshal(m, b)
}
func (m *Prices_BUYS) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Prices_BUYS.Marshal(b, m, deterministic)
}
func (m *Prices_BUYS) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Prices_BUYS.Merge(m, src)
}
func (m *Prices_BUYS) XXX_Size() int {
	return xxx_messageInfo_Prices_BUYS.Size(m)
}
func (m *Prices_BUYS) XXX_DiscardUnknown() {
	xxx_messageInfo_Prices_BUYS.DiscardUnknown(m)
}

var xxx_messageInfo_Prices_BUYS proto.InternalMessageInfo

func (m *Prices_BUYS) GetQuantity() uint32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func (m *Prices_BUYS) GetUnitPrice() uint32 {
	if m != nil {
		return m.UnitPrice
	}
	return 0
}

// Price includes quantity and the high/low price
type Prices_SELLS struct {
	Quantity             uint32   `protobuf:"varint,1,opt,name=quantity,proto3" json:"quantity,omitempty"`
	UnitPrice            uint32   `protobuf:"varint,2,opt,name=unit_price,json=unitPrice,proto3" json:"unit_price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Prices_SELLS) Reset()         { *m = Prices_SELLS{} }
func (m *Prices_SELLS) String() string { return proto.CompactTextString(m) }
func (*Prices_SELLS) ProtoMessage()    {}
func (*Prices_SELLS) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff8ce280720193cf, []int{0, 1}
}

func (m *Prices_SELLS) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Prices_SELLS.Unmarshal(m, b)
}
func (m *Prices_SELLS) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Prices_SELLS.Marshal(b, m, deterministic)
}
func (m *Prices_SELLS) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Prices_SELLS.Merge(m, src)
}
func (m *Prices_SELLS) XXX_Size() int {
	return xxx_messageInfo_Prices_SELLS.Size(m)
}
func (m *Prices_SELLS) XXX_DiscardUnknown() {
	xxx_messageInfo_Prices_SELLS.DiscardUnknown(m)
}

var xxx_messageInfo_Prices_SELLS proto.InternalMessageInfo

func (m *Prices_SELLS) GetQuantity() uint32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func (m *Prices_SELLS) GetUnitPrice() uint32 {
	if m != nil {
		return m.UnitPrice
	}
	return 0
}

type PricesRequest struct {
	Page                 uint32   `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize             uint32   `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PricesRequest) Reset()         { *m = PricesRequest{} }
func (m *PricesRequest) String() string { return proto.CompactTextString(m) }
func (*PricesRequest) ProtoMessage()    {}
func (*PricesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff8ce280720193cf, []int{1}
}

func (m *PricesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PricesRequest.Unmarshal(m, b)
}
func (m *PricesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PricesRequest.Marshal(b, m, deterministic)
}
func (m *PricesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PricesRequest.Merge(m, src)
}
func (m *PricesRequest) XXX_Size() int {
	return xxx_messageInfo_PricesRequest.Size(m)
}
func (m *PricesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PricesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PricesRequest proto.InternalMessageInfo

func (m *PricesRequest) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *PricesRequest) GetPageSize() uint32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func init() {
	proto.RegisterType((*Prices)(nil), "messages.prices")
	proto.RegisterType((*Prices_BUYS)(nil), "messages.prices.BUYS")
	proto.RegisterType((*Prices_SELLS)(nil), "messages.prices.SELLS")
	proto.RegisterType((*PricesRequest)(nil), "messages.pricesRequest")
}

func init() { proto.RegisterFile("commerce_prices.proto", fileDescriptor_ff8ce280720193cf) }

var fileDescriptor_ff8ce280720193cf = []byte{
	// 297 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x91, 0xc1, 0x4b, 0xfb, 0x30,
	0x14, 0xc7, 0x49, 0xd7, 0x8d, 0xed, 0xed, 0xd7, 0x1d, 0x02, 0xfb, 0x11, 0x06, 0x42, 0x1c, 0x08,
	0x15, 0xa4, 0x07, 0xfd, 0x03, 0xc4, 0xa1, 0x07, 0x61, 0x07, 0x49, 0xf1, 0xe0, 0xa9, 0x64, 0xcd,
	0xb3, 0x0b, 0xb4, 0x6b, 0xd7, 0xa4, 0xc8, 0xfc, 0x7b, 0xfd, 0x43, 0xa4, 0x69, 0x57, 0x04, 0x8f,
	0x9e, 0x92, 0xf7, 0xc9, 0x97, 0xcf, 0xcb, 0x4b, 0x60, 0x99, 0x96, 0x45, 0x81, 0x75, 0x8a, 0x49,
	0x55, 0xeb, 0x14, 0x4d, 0x54, 0xd5, 0xa5, 0x2d, 0xe9, 0xb4, 0x40, 0x63, 0x64, 0x86, 0x66, 0xfd,
	0xe5, 0xc1, 0xa4, 0x3b, 0xa2, 0x0b, 0xf0, 0xb4, 0x62, 0x84, 0x93, 0x30, 0x10, 0x9e, 0x56, 0x94,
	0xc3, 0xfc, 0x63, 0xaf, 0x2d, 0xe6, 0xda, 0x58, 0x54, 0xcc, 0xe3, 0x24, 0x9c, 0x8a, 0x9f, 0x88,
	0x5e, 0xc1, 0xe2, 0x1d, 0x6d, 0xba, 0x4f, 0x94, 0xb4, 0x68, 0x75, 0x81, 0x6c, 0xc4, 0x49, 0x38,
	0x12, 0x81, 0xa3, 0x8f, 0x3d, 0xa4, 0xd7, 0xe0, 0xef, 0x9a, 0x93, 0x61, 0x3e, 0x27, 0xe1, 0xfc,
	0x76, 0x19, 0x9d, 0x9b, 0x47, 0xfd, 0x9d, 0x36, 0xaf, 0x6f, 0xb1, 0x70, 0x11, 0x7a, 0x03, 0x63,
	0x83, 0x79, 0x6e, 0xd8, 0xd8, 0x65, 0xff, 0xff, 0xca, 0xc6, 0x4f, 0xdb, 0x6d, 0x2c, 0xba, 0x10,
	0xbd, 0x84, 0x7f, 0x32, 0xcb, 0x6a, 0xcc, 0xa4, 0xc5, 0x44, 0x2b, 0x36, 0xe1, 0x24, 0x9c, 0x89,
	0xf9, 0xc0, 0x9e, 0xd5, 0xea, 0x01, 0xfc, 0x56, 0x4f, 0x57, 0x30, 0x3d, 0x36, 0xf2, 0x60, 0xb5,
	0x3d, 0xf5, 0x23, 0x0e, 0x35, 0xbd, 0x00, 0x68, 0x0e, 0xda, 0x76, 0x4f, 0xe4, 0xe6, 0x0c, 0xc4,
	0xac, 0x25, 0x2f, 0x2d, 0x58, 0x6d, 0x60, 0xec, 0xba, 0xfe, 0xc1, 0xb1, 0xbe, 0x87, 0xa0, 0x1b,
	0x40, 0xe0, 0xb1, 0x41, 0x63, 0x29, 0x05, 0xbf, 0x92, 0x19, 0xf6, 0x1e, 0xb7, 0x6f, 0xfd, 0xed,
	0x1a, 0xeb, 0xcf, 0xb3, 0x61, 0xa8, 0x77, 0x13, 0xf7, 0x71, 0x77, 0xdf, 0x01, 0x00, 0x00, 0xff,
	0xff, 0x35, 0x25, 0x72, 0x3d, 0xd1, 0x01, 0x00, 0x00,
}
