# Gopkg.toml example
#
# Refer to https://golang.github.io/dep/docs/Gopkg.toml.html
# for detailed Gopkg.toml documentation.

[[constraint]]
  name = "github.com/lib/pq"
  version = "1.1.1"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.1"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.21.1"

[prune]
  go-tests = true
  unused-packages = true
